### ISSUE TITLE
SerializableReactiveProperty not reactive to Untiy inspector changes?

### ISSUE THREAD

**Issue by pinkeyyy** [Cysharp/R3#133]
Firstly, great library, so thank you!

However, a small behavioural issue I've encountered which I would like to clarify is intended.

I figured with the introduction of `SerializableReactiveProperty` to expose `ReactiveProperty` to the Unity editor's inspector would also mean that susbcribers would be notified of changes to the property made in the inspector?

This doesn't seem to be the case from my experiments so far, so would like to clarify if this is in the intended behaviour. The docs aren't clear on this from what I've seen so far.

Thanks!

**Comment by neuecc** [comment]
Previously, we handled it with a simple execution from OnDeserialize, but we stopped because there were issues with that approach.
https://github.com/Cysharp/R3/issues/94
I'll try implementing it by executing ForceNotify via reflection after changing the values in the editor inspector (UniRx was implemented this way).
Thank you.
