### ISSUE TITLE
Is it excessive to have OnNextAsync on Subject?

### ISSUE THREAD

**Issue by harayuu9** [Cysharp/R3#185]
When I write code like the following, in reality, OnComplete is called first, so the task itself is cancelled and there is no Console output.

```
var subject = new Subject<string>();

subject.SubscribeAwait(async (text, ct) =>
{
    await Task.Delay(TimeSpan.FromSeconds(1), ct);
    Console.WriteLine(text);
});

subject.OnNext("Hello!");
subject.OnNext("World!");
subject.OnCompleted();

// output
// (none)
```

I believe that in the original Rx, where SubscribeAwait didn't exist, this kind of requirement never came up. However, since R3 actively supports async await, it seems like it would be beneficial to be able to write code like the following:

```
var subject = new Subject<string>();

subject.SubscribeAwait(async (text, ct) =>
{
    await Task.Delay(TimeSpan.FromSeconds(1), ct);
    Console.WriteLine(text);
});

await subject.OnNextAsync("Hello!");
await subject.OnNextAsync("World!");
subject.OnCompleted();

// output
// Hello!
// World!
```

Although it may seem excessive as a feature of Subject, what do you think about this proposal?

**Comment by neuecc** [comment]
That is difficult because Rx is a push type model.
IAsyncEnumerable(UniTaskAsyncEnumerable) might be possible.
MessagePipe is a dedicated system to fulfill such requests (PublishAsync)
https://github.com/Cysharp/MessagePipe

**Comment by harayuu9** [comment]
Thank you very much.
RX is still difficult because it is a Push type.
As for asynchronous event exchange, I will try another method like MessagePipe.

**Comment by Antoshidza** [comment]
Please excuse me for replying in closed issue, but I can't find good solution for the same problem as @harayuu9 described.

In my case I use R3 + UniTask and some unity oriented DI framework. This combination works pretty well for me. However I've faced a case when I want to have `OnNextAsync` to be able to await all subscribers callbacks sequentially.

If try to generalize I need some reactive aggregator which would be subscribe by `Func<T>` instead of `Action<T>`. Such aggregator not only publish some value but also takes responsibility of how it would "pull" results back and in case of async subscribers it could handle `Func<UniTask>` and for my case just await in a loop.

I understand that R3 is a push only model and I request something that is push-pull. But I have doubts about proposed solutions either. I've checked `UniTaskAsyncEnumerable` and MessagePipe and I can't figure out how to setup things to get what I've described here, please forgive me that. Also MessagePipe seems to have dependency with particular DI.

Such functionality could also be implemented as `List<Func<UniTask>>` but then I lose all this `Subscribe().AddTo` handy syntax.

**Comment by Antoshidza** [comment]
> If the pipeline is fixed, it could be that the UniTaskCompletionSource is kicked by SubscribeAwait.

If I understand you correctly in proposed approach I should pass `UniTaskCompletionSource` as pushed value like
```csharp
var utcs = new UniTaskCompletionSource();
var reactiveSubj = new Subject<UniTaskCompletionSource>();
_reactiveSubj.SubscribeAwait(async (utcs, ct) =>
{
    await UniTask.NextFrame(ct);
    utcs.TrySetResult();
});
_reactiveSubj.OnNext(utcs);
await utcs.Task;
```
But then only the first subscriber set `UniTaskCompletionSource` to "complete' state and publisher won't await others
