### ISSUE TITLE
Want to flow the elements of the array one frame at a time

### ISSUE THREAD

**Issue by kochounoyume** [Cysharp/R3#222]
As a goal, I want to do what the title says.

For example, the following source code does not work well in practice (because Complete is issued inside `ToObservable()`), but it may convey the image.

Any good ideas?

```cs
using Cysharp.Threading.Tasks;
using R3;
using UnityEngine;

public sealed class Test : MonoBehaviour
{
    void Start()
    {
        string[] array = { "a", "b", "c" };
        array
            .ToObservable()
            .SubscribeAwait(static async (element, token) =>
            {
                Debug.Log(element);
                await UniTask.Yield(token);
            }, AwaitOperation.Sequential);
    }
}

**Comment by neuecc** [comment]
Because the default cancelOnCompleted of SubscribeAwait has been changed, I think it is now possible to output all elements.

Showing sample is sequential, each element is output one at a time, and it is delayed by one frame with UniTask.Yield, so it does not become one frame.
If you want to make all elements one frame, there are also means such as ToArray to solidify or ChunkFrame to control.
