### ISSUE TITLE
Request feature: AsyncPublisher

### ISSUE THREAD

**Issue by TORISOUP** [Cysharp/R3#271]
There is a `SubscribeAwait` that can wait for results asynchronously, but the Publish side can only call OnNext synchronously.
It would be useful to be able to await asynchronous value consumption on the Subscriber side on the Publish side (like IAsyncPublisher in MessagePipe)

**Comment by neuecc** [comment]
For example, is this the kind of API you're looking for?

```csharp
var asyncPublisher = new AsyncPublisher();

// consumer(asyncPublisher is Observable<T>)
asyncPublisher.Where().Select().SubscribeAwait(/* ... */);

// producer
await asyncPublisher.OnNextAsync();
```

There are several difficult here.
First, the downstream operations (Subscribe/SubscribeAwait) have no knowledge of upstream operations,
so there's no way to communicate completion (TrySetResult) back to the AsyncPublisher's OnNextAsync at the very top of the chain.

Another issue is that when there are time-shift operators in the middle (like Delay), there's no way to determine when exactly the OnNextAsync completion should occur.

MessagePipe is able to handle this because its interface itself has OnNextAsync, allowing it to chain completion notifications from the bottom layer back up to the top.
However, finding a way to add this to the OnNext chain is proving difficult.

If done manually, you could handle it with a wrapper like this:

```csharp
// asyncPublisher has ManualResetValueTaskSourceCore
var asyncPublisher = new AsyncPublisher();

// consumer
asyncPublisher.Where().Select().SubscribeAwait(
{
    asyncPublisher.SetResult(); // call ManualResetValueTaskSourceCore.SetResult
});

// producer, OnNextAsync calls ManualResetValueTaskSourceCore.Reset() before subject.OnNext
await asyncPublisher.OnNextAsync();
```

Based on this idea, making everything process automatically "in a nice way" seems difficult.

**Comment by TORISOUP** [comment]
Thank you for your answer. Yes, I assumed such an API.

However, I understand that it is difficult to handle due to the Observable mechanism.
Since it is difficult to maintain consistency with the existing Observable, could there be an approach towards not incorporating it into the Observable? 

For example, adding something like `MessagePipe.IAsyncPublisher` to R3 as an extra feature like `UniRx.AsyncMessageBroker`. Or improve connectivity between MessagePipe and R3, etc.

**Comment by neuecc** [comment]
If it is not observable, I don't think it is a good idea to incorporate it into the core of R3.
That would not be essentially different from using MessagePipe or other alternatives.

As I mentioned earlier, I can't find a good approach to improving connectivity.

**Comment by TORISOUP** [comment]
I agree that there is no need to force R3 to incorporate things that can be accomplished with other libraries.
I will try to solve this problem with a combination of `ManualResetValueTaskSourceCore` and others.

Thank you for your response.  I close this issue.
