### ISSUE TITLE
Missing operators

### ISSUE THREAD

**Issue by eiparfenov** [Cysharp/R3#83]
There is a link to [Reactive X Operator documentation](https://reactivex.io/documentation/operators.html) in readme, but not all of them are implemented in this version (ex. [Join](https://reactivex.io/documentation/operators/join.html), [GroupBy](https://reactivex.io/documentation/operators/groupby.html)). Are there plans to implement other operators?

**Comment by neuecc** [comment]
I intentionally omitted items that generate Observables internally due to concerns about performance and leaks.
I will not implement something just because it is listed.
However, if you are using it and can explain the demand, I might consider bringing it back.

**Comment by eugbaranov** [comment]
I tried migrating an existing application to R3 but realised that I can't because of missing `GroupBy`.
We subscribe to data which is steaming continuously but semantically within that stream there are bursts of messages send for the same topic. E.g. imagine sequence: `A1 A2 A3 B1 B2 B3 B4 C1 C2 C3 A4 A5 A6 A7`
I want to buffer and process `A1 A2 A3` and `B1 B2 B3 B4` together as their own group (as they have complimentary data) but the problem is that I don't know how many A's and B's I'll receive and you can only observe bursts if you group messages.

**Comment by neuecc** [comment]
Since GroupBy is a frequently requested operator, it's worth considering.
While I think it's an operator that has some issues in terms of performance and subscription management, I'd like to explore if there's a way to make it work effectively.
