### ISSUE TITLE
Feedback: ReadOnlyReactiveProperty<T> is a fairly long name

### ISSUE THREAD

**Issue by Niels-Wosylus** [Cysharp/R3#89]
I was toying with adopting a reactive style using R3, and I found myself using reactive properties everywhere. To ensure encapsulation we need to use the read only variant. For something used so often, I found that "ReadOnlyReactiveProperty<T>" is an uncomfortably long name. 

Since R3 uses abstract base classes, it becomes tricky to wrap it in something like "ICell<T>" or "IReactive<T>" without losing all the extension methods.

This is just a personal observation from someone trying to adopt R3. I don't know the correct approach to this problem. Keeping the descriptive name makes sense for many reasons, but as as user I wish we could have something shorter.

**Comment by neuecc** [comment]
I understand, I also searched for a short name at first but couldn't find one that fit.
In Kotlin, anonymous is ReadOnly, and with classifications like MutableStateFlow and StateFlow, you end up writing similar code.

```kotlin
private val _uiState = MutableStateFlow(LatestNewsUiState.Success(emptyList()))
val uiState: StateFlow<LatestNewsUiState> = _uiState
```

In the case of C#, since anonymous becomes Mutable, having something like ReactiveProperty and ReadOnlyReactiveProperty is not so unnatural, I guess.
But, it's long.
